### `Load all required Libraries`

In [42]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_rows', 500,'display.max_columns', 500,'display.width', 1000)


In [271]:
#Get the data
lend  = pd.read_csv("loan.csv",encoding="UTF-8")
lend.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39717 entries, 0 to 39716
Columns: 111 entries, id to total_il_high_credit_limit
dtypes: float64(74), int64(13), object(24)
memory usage: 33.6+ MB


##  <span style='background :cyan' > Findings:- </span>
- `We have 39717 rows.`
- `111 columns.`

In [272]:
print(lend.columns)

Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv', 'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       ...
       'num_tl_90g_dpd_24m', 'num_tl_op_past_12m', 'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'pub_rec_bankruptcies', 'tax_liens', 'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit', 'total_il_high_credit_limit'], dtype='object', length=111)


In [273]:
lend.head()

id  member_id  loan_amnt  funded_amnt  funded_amnt_inv        term int_rate  installment grade sub_grade                 emp_title emp_length home_ownership  annual_inc verification_status issue_d  loan_status pymnt_plan                                                url                                               desc         purpose                 title zip_code addr_state    dti  delinq_2yrs earliest_cr_line  inq_last_6mths  mths_since_last_delinq  mths_since_last_record  open_acc  pub_rec  revol_bal revol_util  total_acc initial_list_status  out_prncp  out_prncp_inv   total_pymnt  total_pymnt_inv  total_rec_prncp  total_rec_int  total_rec_late_fee  recoveries  collection_recovery_fee last_pymnt_d  last_pymnt_amnt next_pymnt_d last_credit_pull_d  collections_12_mths_ex_med  mths_since_last_major_derog  policy_code application_type  annual_inc_joint  dti_joint  verification_status_joint  acc_now_delinq  tot_coll_amt  tot_cur_bal  open_acc_6m  open_il_6m  open_il_12m  \
0  1077501    1296599       5000         5000           4975.0   36 months   10.65%       162.87     B        B2                       NaN  10+ years           RENT     24000.0            Verified  Dec-11   Fully Paid          n  https://lendingclub.com/browse/loanDetail.acti...    Borrower added on 12/22/11 > I need to upgra...     credit_card              Computer    860xx         AZ  27.65            0           Jan-85               1                     NaN                     NaN         3        0      13648     83.70%          9                   f       0.00           0.00   5863.155187          5833.84          5000.00         863.16                0.00        0.00                     0.00       Jan-15           171.62          NaN             May-16                         0.0                          NaN            1       INDIVIDUAL               NaN        NaN                        NaN               0           NaN          NaN          NaN         NaN          NaN   
1  1077430    1314167       2500         2500           2500.0   60 months   15.27%        59.83     C        C4                     Ryder   < 1 year           RENT     30000.0     Source Verified  Dec-11  Charged Off          n  https://lendingclub.com/browse/loanDetail.acti...    Borrower added on 12/22/11 > I plan to use t...             car                  bike    309xx         GA   1.00            0           Apr-99               5                     NaN                     NaN         3        0       1687      9.40%          4                   f       0.00           0.00   1008.710000          1008.71           456.46         435.17                0.00      117.08                     1.11       Apr-13           119.66          NaN             Sep-13                         0.0                          NaN            1       INDIVIDUAL               NaN        NaN                        NaN               0           NaN          NaN          NaN         NaN          NaN   
2  1077175    1313524       2400         2400           2400.0   36 months   15.96%        84.33     C        C5                       NaN  10+ years           RENT     12252.0        Not Verified  Dec-11   Fully Paid          n  https://lendingclub.com/browse/loanDetail.acti...                                                NaN  small_business  real estate business    606xx         IL   8.72            0           Nov-01               2                     NaN                     NaN         2        0       2956     98.50%         10                   f       0.00           0.00   3005.666844          3005.67          2400.00         605.67                0.00        0.00                     0.00       Jun-14           649.91          NaN             May-16                         0.0                          NaN            1       INDIVIDUAL               NaN        NaN                        NaN               0           NaN          NaN          NaN         NaN          NaN   
3  1076863    127717

In [274]:
#check missing value percentages 
#round the percentages to 2 decimal points.
missing_columns = round((lend.isna().sum()/len(lend))*100,2)
print(missing_columns.sort_values(ascending=False))


total_il_high_credit_limit        100.00
mo_sin_old_rev_tl_op              100.00
bc_util                           100.00
bc_open_to_buy                    100.00
avg_cur_bal                       100.00
acc_open_past_24mths              100.00
inq_last_12m                      100.00
total_cu_tl                       100.00
inq_fi                            100.00
total_rev_hi_lim                  100.00
all_util                          100.00
max_bal_bc                        100.00
open_rv_24m                       100.00
open_rv_12m                       100.00
il_util                           100.00
total_bal_il                      100.00
mths_since_rcnt_il                100.00
open_il_24m                       100.00
open_il_12m                       100.00
open_il_6m                        100.00
open_acc_6m                       100.00
tot_cur_bal                       100.00
tot_coll_amt                      100.00
total_bc_limit                    100.00
dti_joint       

##  <span style='background :cyan' > Findings:- </span>
- ` Many columns have 100% null values.`
- ` We will drop columns having more than 50% null values.`

In [275]:
#Create a List more than 50% null values columns
drop_coulmns = list(missing_columns[missing_columns>50].index)
#check columns having more than 50% null values
print(f"No of columns having more than 50% missing values:{len(drop_columns)}")
print("-----------------------------")
print(missing_columns[missing_columns>50].sort_values(ascending=False))

No of columns having more than 50% missing values:57
-----------------------------
total_il_high_credit_limit        100.00
il_util                           100.00
bc_open_to_buy                    100.00
avg_cur_bal                       100.00
acc_open_past_24mths              100.00
inq_last_12m                      100.00
total_cu_tl                       100.00
inq_fi                            100.00
total_rev_hi_lim                  100.00
all_util                          100.00
max_bal_bc                        100.00
open_rv_24m                       100.00
open_rv_12m                       100.00
total_bal_il                      100.00
total_bc_limit                    100.00
mths_since_rcnt_il                100.00
open_il_24m                       100.00
open_il_12m                       100.00
open_il_6m                        100.00
open_acc_6m                       100.00
tot_cur_bal                       100.00
tot_coll_amt                      100.00
verification_st

In [276]:
#Drop 50% missing values columns 
lend.drop(drop_coulmns,axis=1,inplace=True)

In [277]:
lend.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39717 entries, 0 to 39716
Data columns (total 54 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   id                          39717 non-null  int64  
 1   member_id                   39717 non-null  int64  
 2   loan_amnt                   39717 non-null  int64  
 3   funded_amnt                 39717 non-null  int64  
 4   funded_amnt_inv             39717 non-null  float64
 5   term                        39717 non-null  object 
 6   int_rate                    39717 non-null  object 
 7   installment                 39717 non-null  float64
 8   grade                       39717 non-null  object 
 9   sub_grade                   39717 non-null  object 
 10  emp_title                   37258 non-null  object 
 11  emp_length                  38642 non-null  object 
 12  home_ownership              39717 non-null  object 
 13  annual_inc                  397

##  <span style='background :cyan' > Findings:- </span>
-`We have dropped 57 columns out of 111 coumns`.


In [278]:
missing_columns = lend.isna().sum()

In [279]:
# Check all the columns having atleast 1 missing values
print(missing_columns[missing_columns>0].index)

Index(['emp_title', 'emp_length', 'desc', 'title', 'revol_util', 'last_pymnt_d', 'last_credit_pull_d', 'collections_12_mths_ex_med', 'chargeoff_within_12_mths', 'pub_rec_bankruptcies', 'tax_liens'], dtype='object')


In [280]:
# All columns having atleast ONE missing value. Collect those columns
columns_miss = missing_columns[missing_columns>0].index

In [281]:
lend[columns_miss].head(20)

emp_title emp_length                                               desc                                  title revol_util last_pymnt_d last_credit_pull_d  collections_12_mths_ex_med  chargeoff_within_12_mths  pub_rec_bankruptcies  tax_liens
0                                   NaN  10+ years    Borrower added on 12/22/11 > I need to upgra...                               Computer     83.70%       Jan-15             May-16                         0.0                       0.0                   0.0        0.0
1                                 Ryder   < 1 year    Borrower added on 12/22/11 > I plan to use t...                                   bike      9.40%       Apr-13             Sep-13                         0.0                       0.0                   0.0        0.0
2                                   NaN  10+ years                                                NaN                   real estate business     98.50%       Jun-14             May-16                         0.0                       0.0                   0.0        0.0
3                   AIR RESOURCES BOARD  10+ years    Borrower added on 12/21/11 > to pay for prop...                               personel        21%       Jan-15             Apr-16                         0.0                       0.0                   0.0        0.0
4              University Medical Group     1 year    Borrower added on 12/21/11 > I plan on combi...                               Personal     53.90%       May-16             May-16                         0.0                       0.0                   0.0        0.0
5                  Veolia Transportaton    3 years                                                NaN  My wedding loan I promise to pay back     28.30%       Jan-15             Jan-16                         0.0                       0.0                   0.0        0.0
6             Southern Star Photography    8 years    Borrower added on 12/18/11 > I am planning o...                                   Loan     85.60%       May-16             May-16                         0.0                       0.0                   0.0        0.0
7                       MKC Accounting     9 years    Borrower added on 12/16/11 > Downpayment for...                        Car Downpayment     87.50%       Jan-15             Dec-14                         0.0                       0.0                   0.0        0.0
8                                   NaN    4 years    Borrower added on 12/21/11 > I own a small h...   Expand Business & Buy Debt Portfolio     32.60%       Apr-12             Aug-12                         0.0                       0.0                   0.0        0.0
9                             Starbucks   < 1 year    Borrower added on 12/16/11 > I'm trying to b...            Building my credit history.     36.50%       Nov-12             Mar-13                         0.0                       0.0                   0.0        0.0
10                Southwest Rural metro    5 years    Borrower added on 12/15/11 > I had recived a...             High intrest Consolidation     20.60%       Jun-13             Dec-15                         0.0                       0.0                   0.0        0.0
11                                 UCLA  10+ years                                                NaN                          Consolidation     67.10%       Sep-13             Aug-13                         0.0                       0.0                   0.0        0.0
12  Va. Dept of Conservation/Recreation   < 1 year    Borrower added on 12/15/11 > Plan to pay off...                                freedom     91.70%       Jul-12             Nov-12                         0.0                       0.0                   0.0        0.0
13                               Target    3 years    Borrower added on 12/19/11 > I intend to pay...                          citicard fund     43.10%       Jan-15             May-16                         0.0                       0.

##  <span style='background :cyan' > Findings:- </span>

- `Below columns have ATLEAST ONE missing values`.
- `Inspect each column indivisually`.

    - emp_title 
    - emp_length  
    - desc
    - title
    - revol_util
    - last_pymnt_d 
    - last_credit_pull_d
    - collections_12_mths_ex_med
    - chargeoff_within_12_mths 
    - pub_rec_bankruptcies
    - tax_liens


<b> `"emp_title" column` <b>

In [282]:
# Inspect "emp_title" columns 
lend["emp_title"].isna().sum()
print("No of missing value in emp_title:",lend["emp_title"].isna().sum())
print("------------------------------")
print(lend["emp_title"].head(10))
print("------------------------------")
print(lend["emp_title"].tail(10))
print("---------------------------")


No of missing value in emp_title: 2459
------------------------------
0                          NaN
1                        Ryder
2                          NaN
3          AIR RESOURCES BOARD
4     University Medical Group
5         Veolia Transportaton
6    Southern Star Photography
7              MKC Accounting 
8                          NaN
9                    Starbucks
Name: emp_title, dtype: object
------------------------------
39707            Stark and Roth Inc
39708               Millenium Group
39709                Self-Employeed
39710             Rush Univ Med Grp
39711           A. F. Wolfers, Inc.
39712               FiSite Research
39713    Squarewave Solutions, Ltd.
39714                           NaN
39715                           NaN
39716              Evergreen Center
Name: emp_title, dtype: object
---------------------------


In [283]:
lend["emp_title"].unique()

array([nan, 'Ryder', 'AIR RESOURCES BOARD', ..., 'FiSite Research',
       'Squarewave Solutions, Ltd.', 'Evergreen Center'], dtype=object)

- <b>`Mark NAN value as "missing" in emp_title column.`<b>


In [284]:
lend["emp_title"].fillna(value = 'missing',inplace = True)

<b> `"emp_length" column` <b>

In [285]:
print("No of missing values in emp_length:",lend["emp_length"].isna().sum())
print("----------------------------------------------")
print(lend["emp_length"].unique())
print("----------------------------------------------")
print(lend["emp_title"].value_counts())

No of missing values in emp_length: 1075
----------------------------------------------
['10+ years' '< 1 year' '1 year' '3 years' '8 years' '9 years' '4 years'
 '5 years' '6 years' '2 years' '7 years' nan]
----------------------------------------------
missing                           2459
US Army                            134
Bank of America                    109
IBM                                 66
AT&T                                59
                                  ... 
bren-tronics                         1
McLane                               1
Santa Fe College                     1
Clemens Bruns Schaub Architect       1
Bechtel                              1
Name: emp_title, Length: 28821, dtype: int64


<b> `Dropping rows where  emp_length is NaN.` <br>
    `It is employee years of work.`<br>
`Possible values are between 0 and 10 where 0 means less than one year and 10 means ten or more years. `


In [286]:
lend = lend[~lend["emp_length"].isna()]

<b> `"desc" column` <b>

In [287]:
print("Missing values in \"desc\" :",lend["desc"].isna().sum())
print("------------------------------------------------------------")
print(lend["desc"][1])
print("------------------------------------------------------------")
print(lend["title"][1])

Missing values in "desc" : 12495
------------------------------------------------------------
  Borrower added on 12/22/11 > I plan to use this money to finance the motorcycle i am looking at. I plan to have it paid off as soon as possible/when i sell my old bike. I only need this money because the deal im looking at is to good to pass up.<br><br>  Borrower added on 12/22/11 > I plan to use this money to finance the motorcycle i am looking at. I plan to have it paid off as soon as possible/when i sell my old bike.I only need this money because the deal im looking at is to good to pass up. I have finished college with an associates degree in business and its takingmeplaces<br>
------------------------------------------------------------
bike


- `"desc" is synonimous to "title" column.`
- `Hence we can drop this columns and keep "title" column.`

In [288]:
lend.drop(columns=['desc'],inplace=True)

In [289]:
lend["title"].head(10)

0                                 Computer
1                                     bike
2                     real estate business
3                                 personel
4                                 Personal
5    My wedding loan I promise to pay back
6                                     Loan
7                          Car Downpayment
8     Expand Business & Buy Debt Portfolio
9              Building my credit history.
Name: title, dtype: object

- <b>`Mark NAN value as "missing" in title column.`<b>


In [290]:
print(lend["title"].unique())
lend["title"].fillna(value = "missing",inplace=True)

['Computer' 'bike' 'real estate business' ... 'Retiring credit card debt'
 'MBA Loan Consolidation' 'JAL Loan']


In [291]:
lend["revol_util"].head(10)
lend["revol_util"].isna().sum()


47

In [292]:
lend = lend[~lend["revol_util"].isna()]


In [293]:
lend=lend[~lend["last_pymnt_d"].isna()]

In [294]:
lend["last_credit_pull_d"].isna().sum()
# lend["last_credit_pull_d"].head(10)

2

In [295]:
lend=lend[~lend["last_credit_pull_d"].isna()]

In [296]:
lend["collections_12_mths_ex_med"].unique()

array([ 0., nan])

In [297]:
lend["chargeoff_within_12_mths"].unique()

array([ 0., nan])

In [298]:
lend["tax_liens"].unique()

array([ 0., nan])

In [300]:
print(lend["pub_rec_bankruptcies"].unique())
print("----------------------")
print(lend["pub_rec_bankruptcies"].value_counts())

[ 0.  1.  2. nan]
----------------------
0.0    36272
1.0     1556
2.0        7
Name: pub_rec_bankruptcies, dtype: int64


##  <span style='background :cyan' > Findings:- </span>
- `Drop below columns as those have either value '0' or 'NaN' and will be insignificant to our analysis.`<br>
   - collections_12_mths_ex_med <br>
   -  chargeoff_within_12_mths <br>
   -  pub_rec_bankruptcies <br>
   -  tax_liens

In [301]:
list_cols = ['collections_12_mths_ex_med', 'chargeoff_within_12_mths', 'pub_rec_bankruptcies', 'tax_liens']
lend.drop(list_cols,axis=1,inplace=True)

In [302]:
lend.isna().sum()

id                         0
member_id                  0
loan_amnt                  0
funded_amnt                0
funded_amnt_inv            0
term                       0
int_rate                   0
installment                0
grade                      0
sub_grade                  0
emp_title                  0
emp_length                 0
home_ownership             0
annual_inc                 0
verification_status        0
issue_d                    0
loan_status                0
pymnt_plan                 0
url                        0
purpose                    0
title                      0
zip_code                   0
addr_state                 0
dti                        0
delinq_2yrs                0
earliest_cr_line           0
inq_last_6mths             0
open_acc                   0
pub_rec                    0
revol_bal                  0
revol_util                 0
total_acc                  0
initial_list_status        0
out_prncp                  0
out_prncp_inv 

In [303]:
lend.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 38531 entries, 0 to 39716
Data columns (total 49 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       38531 non-null  int64  
 1   member_id                38531 non-null  int64  
 2   loan_amnt                38531 non-null  int64  
 3   funded_amnt              38531 non-null  int64  
 4   funded_amnt_inv          38531 non-null  float64
 5   term                     38531 non-null  object 
 6   int_rate                 38531 non-null  object 
 7   installment              38531 non-null  float64
 8   grade                    38531 non-null  object 
 9   sub_grade                38531 non-null  object 
 10  emp_title                38531 non-null  object 
 11  emp_length               38531 non-null  object 
 12  home_ownership           38531 non-null  object 
 13  annual_inc               38531 non-null  float64
 14  verification_status   

In [265]:
# Check row wise null values
# (lend.isna().sum(axis = 1)>4).sum()
#We do not have much rows having so mnay null values

0

In [266]:
lend["member_id"].unique()

array([1296599, 1314167, 1313524, ...,   90390,   89243,   86999],
      dtype=int64)

In [267]:
lend["zip_code"].unique()

array(['860xx', '309xx', '606xx', '917xx', '972xx', '852xx', '280xx',
       '900xx', '958xx', '774xx', '853xx', '913xx', '245xx', '951xx',
       '641xx', '921xx', '067xx', '890xx', '770xx', '335xx', '799xx',
       '605xx', '150xx', '326xx', '564xx', '141xx', '080xx', '330xx',
       '974xx', '934xx', '405xx', '946xx', '445xx', '850xx', '604xx',
       '292xx', '088xx', '180xx', '029xx', '700xx', '010xx', '441xx',
       '104xx', '061xx', '616xx', '947xx', '914xx', '765xx', '980xx',
       '017xx', '752xx', '787xx', '077xx', '540xx', '225xx', '440xx',
       '437xx', '559xx', '912xx', '325xx', '300xx', '923xx', '352xx',
       '013xx', '146xx', '074xx', '786xx', '937xx', '331xx', '115xx',
       '191xx', '114xx', '908xx', '902xx', '992xx', '750xx', '950xx',
       '329xx', '226xx', '614xx', '802xx', '672xx', '083xx', '100xx',
       '926xx', '931xx', '712xx', '060xx', '707xx', '342xx', '895xx',
       '430xx', '919xx', '996xx', '891xx', '935xx', '801xx', '928xx',
       '233xx', '927

In [171]:
lend["addr_state"].value_counts()

CA    7071
NY    3803
FL    2862
TX    2715
NJ    1842
IL    1522
PA    1511
VA    1403
GA    1396
MA    1339
OH    1217
MD    1044
AZ     876
WA     839
CO     791
NC     785
CT     750
MI     719
MO     683
MN     612
NV     496
SC     472
WI     458
OR     450
AL     450
LA     436
KY     324
OK     299
KS     270
UT     258
AR     244
DC     212
RI     198
NM     189
WV     176
HI     173
NH     171
DE     113
MT      85
WY      83
AK      80
SD      63
VT      54
MS      19
TN      17
IN       9
ID       6
NE       5
IA       5
ME       3
Name: addr_state, dtype: int64

In [172]:
lend.head(20)

id  member_id  loan_amnt  funded_amnt  funded_amnt_inv        term int_rate  installment grade sub_grade                            emp_title emp_length home_ownership  annual_inc verification_status issue_d  loan_status pymnt_plan                                                url             purpose                                  title zip_code addr_state    dti  delinq_2yrs earliest_cr_line  inq_last_6mths  open_acc  pub_rec  revol_bal revol_util  total_acc initial_list_status  out_prncp  out_prncp_inv   total_pymnt  total_pymnt_inv  total_rec_prncp  total_rec_int  total_rec_late_fee  recoveries  collection_recovery_fee last_pymnt_d  last_pymnt_amnt last_credit_pull_d  policy_code application_type  acc_now_delinq  delinq_amnt
0   1077501    1296599       5000         5000           4975.0   36 months   10.65%       162.87     B        B2                              missing  10+ years           RENT    24000.00            Verified  Dec-11   Fully Paid          n  https://lendingclub.com/browse/loanDetail.acti...         credit_card                               Computer    860xx         AZ  27.65            0           Jan-85               1         3        0      13648     83.70%          9                   f       0.00           0.00   5863.155187          5833.84          5000.00         863.16                0.00        0.00                   0.0000       Jan-15           171.62             May-16            1       INDIVIDUAL               0            0
1   1077430    1314167       2500         2500           2500.0   60 months   15.27%        59.83     C        C4                                Ryder   < 1 year           RENT    30000.00     Source Verified  Dec-11  Charged Off          n  https://lendingclub.com/browse/loanDetail.acti...                 car                                   bike    309xx         GA   1.00            0           Apr-99               5         3        0       1687      9.40%          4                   f       0.00           0.00   1008.710000          1008.71           456.46         435.17                0.00      117.08                   1.1100       Apr-13           119.66             Sep-13            1       INDIVIDUAL               0            0
2   1077175    1313524       2400         2400           2400.0   36 months   15.96%        84.33     C        C5                              missing  10+ years           RENT    12252.00        Not Verified  Dec-11   Fully Paid          n  https://lendingclub.com/browse/loanDetail.acti...      small_business                   real estate business    606xx         IL   8.72            0           Nov-01               2         2        0       2956     98.50%         10                   f       0.00           0.00   3005.666844          3005.67          2400.00         605.67                0.00        0.00                   0.0000       Jun-14           649.91             May-16            1       INDIVIDUAL               0            0
3   1076863    1277178      10000        10000          10000.0   36 months   13.49%       339.31     C        C1                  AIR RESOURCES BOARD  10+ years           RENT    49200.00     Source Verified  Dec-11   Fully Paid          n  https://lendingclub.com/browse/loanDetail.acti...               other                               personel    917xx         CA  20.00            0           Feb-96               1        10        0       5598        21%         37                   f       0.00           0.00  12231.890000         12231.89         10000.00        2214.92               16.97        0.00                   0.0000       Jan-15           357.48             Apr-16            1       INDIVIDUAL               0            0
4   1075358    1311748       3000         3000           3000.0   60 months   12.69%        67.79     B        B5             University Medical Group     1 year           RENT    80000.00     Source Verified  Dec-11      Current          n  https://lendingcl

In [173]:
lend["pymnt_plan"].value_counts()

n    39598
Name: pymnt_plan, dtype: int64

In [191]:
lend["url"].unique()

# ID and URL is synonimous

array(['https://lendingclub.com/browse/loanDetail.action?loan_id=1077501',
       'https://lendingclub.com/browse/loanDetail.action?loan_id=1077430',
       'https://lendingclub.com/browse/loanDetail.action?loan_id=1077175',
       ...,
       'https://lendingclub.com/browse/loanDetail.action?loan_id=90395',
       'https://lendingclub.com/browse/loanDetail.action?loan_id=90376',
       'https://lendingclub.com/browse/loanDetail.action?loan_id=87023'],
      dtype=object)

In [181]:
# lend[lend["title"]=="missing"][""]
lend["delinq_2yrs"].unique()

array([ 0,  2,  3,  1,  4,  6,  5,  8,  7,  9, 11], dtype=int64)

In [268]:
#Number of derogatory public records ->pub_rec

lend["pub_rec"].value_counts()

0    36547
1     1926
2       49
3        7
4        2
Name: pub_rec, dtype: int64

In [184]:
lend["initial_list_status"].value_counts()

f    39598
Name: initial_list_status, dtype: int64

In [185]:
lend["policy_code"].unique()

array([1], dtype=int64)

In [186]:
lend["policy_code"].value_counts()

1    39598
Name: policy_code, dtype: int64

In [188]:
print(lend["application_type"].unique())
lend["application_type"].value_counts()

['INDIVIDUAL']


INDIVIDUAL    39598
Name: application_type, dtype: int64

In [189]:
lend["acc_now_delinq"].unique()

array([0], dtype=int64)

In [190]:
lend["delinq_amnt"].unique()

array([0], dtype=int64)

In [304]:
lend["funded_amnt"].unique()

array([ 5000,  2500,  2400, ...,   800, 13875, 22350], dtype=int64)

In [305]:
lend["funded_amnt_inv"].unique()

array([4975., 2500., 2400., ...,  200.,   75.,  150.])

In [308]:
lend[["funded_amnt_inv","funded_amnt"]].head(20)

funded_amnt_inv  funded_amnt
0            4975.0         5000
1            2500.0         2500
2            2400.0         2400
3           10000.0        10000
4            3000.0         3000
5            5000.0         5000
6            7000.0         7000
7            3000.0         3000
8            5600.0         5600
9            5350.0         5375
10           6500.0         6500
11          12000.0        12000
12           9000.0         9000
13           3000.0         3000
14          10000.0        10000
15           1000.0         1000
16          10000.0        10000
17           3600.0         3600
18           6000.0         6000
19           9200.0         9200